### ISSUE TITLE
[BUG] 启动streamlit run webui_st.py，报错AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by xiaolechen** [chatchat-space/langchain-ChatGLM#1017]
**AttributeError: 'NoneType' object has no attribute 'get'**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

修改了webui_st.py的代码：
chat_box = st_chatbox(greetings=["模型已成功加载，可以开始对话，或从左侧选择模式后开始对话。"])
改成了
chat_box = ChatBox(greetings=["模型已成功加载，可以开始对话，或从左侧选择模式后开始对话。"])
因为streamlit_chatbox中使用st_chatbox报错，我改成了ChatBox

**复现问题的步骤 / Steps to Reproduce**
1. 执行 streamlit run webui_st.py
2. 模型加载成功，可以看到：模型已成功加载，可以开始对话，或从右侧选择模式后开始对话
3. 然后出现：Uncaught app exception，
Traceback (most recent call last):
  File "/home/name/miniconda3/envs/langchain-ChatGLM/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/name/llm_apps/langchain-ChatGLM/webui_st.py", line 395, in <module>
    chat_box.output_messages()
  File "/home/name/miniconda3/envs/langchain-ChatGLM/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 172, in output_messages
    for msg in self.history:
               ^^^^^^^^^^^^
  File "/home/name/miniconda3/envs/langchain-ChatGLM/lib/python3.11/site-packages/streamlit_chatbox/messages.py", line 64, in history
    return st.session_state.get(self._session_key).get(self._chat_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

页面已经出来一半，就是不能对话。
同样的环境，webui.py启动时成功的

**Comment by VincentLore** [comment]
streamlit_chatbox 需要小于1.0
例如
pip install streamlit_chatbox==0.2.4
