### ISSUE TITLE
没有动过model_config.py中的“LORA_MODEL_PATH_BAICHUAN”这一项内容，却报错

### ISSUE THREAD

**Issue by zhit-W** [chatchat-space/langchain-ChatGLM#1047]
使用llm为chatglm2-6b-32k，使用的Embedding 为m3e-base，启动webui.py报错。报错信息如下：

load_model_config /root/autodl-tmp/chatglm2-6b-32k...
Loading /root/autodl-tmp/chatglm2-6b-32k...
Traceback (most recent call last):
  File "webui.py", line 334, in <module>
    model_status = init_model()
  File "webui.py", line 106, in init_model
    llm_model_ins = shared.loaderLLM()
  File "/root/autodl-tmp/langchain-ChatGLM/models/shared.py", line 39, in loaderLLM
    loaderCheckPoint.reload_model()
  File "/root/autodl-tmp/langchain-ChatGLM/models/loader/loader.py", line 506, in reload_model
    self.model, self.tokenizer = self._load_model()
  File "/root/autodl-tmp/langchain-ChatGLM/models/loader/loader.py", line 132, in _load_model
    if LORA_MODEL_PATH_BAICHUAN:
UnboundLocalError: local variable 'LORA_MODEL_PATH_BAICHUAN' referenced before assignment

**Comment by zhit-W** [comment]
代码是2023-08-11刚刚更新的

**Comment by Peri-albert** [comment]
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/49804947/aefca10d-5244-4c49-bf02-c6abba5d835a)

**Comment by hi909hi** [comment]
我也是相同的问题，应该是更新错了，可以手动给赋值一下

**Comment by zhit-W** [comment]
需要改一下loader.py，就按照上面贴出来的改就好了。

**Comment by litongyun233** [comment]
加入：from configs.model_config import LLM_DEVICE,LLM_MODEL,LORA_MODEL_PATH_BAICHUAN
