### ISSUE TITLE
[BUG] webui能正常加载线上模型，api.py加载不了，会报错

### ISSUE THREAD

**Issue by fhyu** [chatchat-space/langchain-ChatGLM#1051]
Traceback (most recent call last):
  File "/root/autodl-tmp/langchain-ChatGLM/api.py", line 590, in <module>
    api_start(args.host, args.port, ssl_keyfile=args.ssl_keyfile, ssl_certfile=args.ssl_certfile)
  File "/root/autodl-tmp/langchain-ChatGLM/api.py", line 529, in api_start
    llm_model_ins = shared.loaderLLM()
  File "/root/autodl-tmp/langchain-ChatGLM/models/shared.py", line 39, in loaderLLM
    loaderCheckPoint.reload_model()
  File "/root/autodl-tmp/langchain-ChatGLM/models/loader/loader.py", line 506, in reload_model
    self.model, self.tokenizer = self._load_model()
  File "/root/autodl-tmp/langchain-ChatGLM/models/loader/loader.py", line 152, in _load_model
    LoaderClass.from_pretrained(checkpoint,
  File "/root/pyenv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/pyenv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/pyenv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/pyenv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/pyenv/lib/python3.10/site-packages/transformers/utils/hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm-6b-int4 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by TCHSDUFH** [comment]
挂梯子或者多试几次

**Comment by imClumsyPanda** [comment]
代码已更新至0.2.0版本，重新设计了api，并基于api开展的webui开发。
